-- This is a temporary code snippet / will be replaced by a Datastore later 
local codes = {
	{ Code = "WELCOME", RewardType = "Coins", RewardAmount = 100 },
	{ Code = "BONUS50", RewardType = "Coins", RewardAmount = 50 },
	{ Code = "GIFT100", RewardType = "Gems", RewardAmount = 100 },
	{ Code = "LUCKYDAY", RewardType = "Coins", RewardAmount = 200 },
	{ Code = "SUPERSTAR", RewardType = "Gems", RewardAmount = 150 },
    { Code = "TEST", RewardType = "Pet", RewardAmount = 'Dog' },
}

return codes
