local Config = {
    Teams = {
        Red = {
            Name = "Red",
            TeamColor = BrickColor.Red(),
        },
        Blue = {
            Name = "Blue",
            TeamColor = BrickColor.Blue(),
        },
    },

    MaxPlayersPerTeam = 25,
    BaseStudsPerSecond = 1,
    CoinsPerBlock = 1,
    TotalStairs = 80,
    RoundTime = 30,
    StudsPerSecondBaseCost = 10,
    CoinsPerBlockBaseCost = 20,
}

return Config