local Config = {
    Teams = {
        Red = {
            Name = "Red",
            TeamColor = BrickColor.Red(),
            Color3 = Color3.fromRGB(222, 70, 70),
        },
        Blue = {
            Name = "Blue",
            TeamColor = BrickColor.Blue(),
            Color3 = Color3.fromRGB(58, 100, 248),

        },
    },

    MaxPlayersPerTeam = 25,
    BaseStudsPerSecond = 1,
    CoinsPerBlock = 1,
    TotalStairs = 80,
    RoundTime = 3000,
    StudsPerSecondBaseCost = 10,
    CoinsPerBlockBaseCost = 20,
    SpawnTime = 5,
    Intermission = 300,
}

return Config